difference_and_sum: difference_and_sum.o
	gcc -ansi -Wall -pedantic -o difference_and_sum difference_and_sum.o
difference_and_sum.o: difference_and_sum.c
	gcc -ansi -Wall -pedantic -o difference_and_sum.o -c difference_and_sum.c